In [1]:
import pandas as pd
import requests
import json

from scripts.nav_utils import fetch_nav_history, build_portfolio_matrix

In [2]:
mf_df = pd.read_csv('data/mutual_fund_info.csv')

In [3]:
mf_df.describe(include='all')

,AMC,Code,Scheme Name,Scheme Type,Scheme Category,Scheme NAV Name,Scheme Minimum Amount,Launch Date,Closure Date,ISIN Div Payout/ ISIN GrowthISIN Div Reinvestment
count,16456,16456.000000,16456,16456,16456,16456,16430,16435,3875,15047
unique,57,NaN,3760,3,104,16419,575,2290,684,15039
top,ICICI Prudential Asset Management Company Limited,NaN,Franklin India Short-Term Income Plan (no. of ...,Open Ended,Income,Kotak Bond-Deposit-Dividend,5000,01-Jan-2013,20-Sep-2007,INF204KA1US6
freq,3333,NaN,45,10258,6065,4,4979,75,50,2
mean,NaN,137167.333495,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,15525.566786,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,100033.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,126249.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,142412.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,149661.250000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,154761.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
mf_df.columns

Index(['AMC', 'Code', 'Scheme Name', 'Scheme Type', 'Scheme Category',
       'Scheme NAV Name', 'Scheme Minimum Amount', 'Launch Date',
       ' Closure Date', 'ISIN Div Payout/ ISIN GrowthISIN Div Reinvestment'],
      dtype='str')

# fund universe

In [5]:
mid_cap = [
    "WhiteOak Capital Mid Cap Fund Direct Plan Growth",
    "HSBC Midcap Fund - Direct Growth",
    "Invesco India Mid Cap Fund - Direct Plan - Growth Option",
    "ICICI Prudential Mid Cap Fund - Direct Plan -  Growth",
    "Union Midcap Fund - Direct Plan - Growth Option",
    "HDFC Mid Cap Fund - Growth Option - Direct Plan",
    "Kotak Mid Cap Fund - Direct Plan - Growth",
    "Mirae Asset Midcap Fund - Direct Plan - Growth",
    "Nippon India Growth Mid Cap Fund - Direct Plan Growth Plan - Growth Option",
    "Edelweiss Mid Cap Fund - Direct Plan - Growth Option",
]

small_cap = [
    "Motilal Oswal Small Cap Fund - Direct - Growth",
    "Union Small Cap Fund - Direct Plan - Growth Option",
    "BANK OF INDIA Small Cap Fund Direct Plan Growth",
    "ITI Small Cap Fund - Direct Plan - Growth Option",
    "DSP Small Cap Fund - Direct Plan - Growth",
    "Invesco India Small Cap Fund - Direct Plan - Growth",
    "PGIM India Small Cap Fund - Direct Plan- Growth Option",
    "Sundaram Small Cap Fund Direct Plan - Growth",
    "Aditya Birla Sun Life Small Cap Fund - Growth - Direct Plan",
    "quant Small Cap Fund - Growth Option - Direct Plan",
]

debt = [
    "Aditya Birla Sun Life Medium Term Fund - Growth - Direct Plan",
    "DSP Credit Risk Fund - Direct Plan - Growth",
    "BANK OF INDIA Short Term Income Fund-Direct Plan- Growth",
    "HDFC Income Plus Arbitrage Active FOF - Growth Option - Direct Plan",
    "ICICI Prudential Dynamic Bond Fund - Direct Plan -  Growth",
    "Nippon India Credit Risk Fund - Direct Plan - Growth Plan",
    "ICICI Prudential Medium Term Fund - Direct Plan - Growth",
    "Nippon India Corporate Bond Fund - Direct Plan Growth Plan - Growth Option",
    "Axis Corporate Bond Fund - Direct Plan Growth",
    "Franklin India Corporate Debt Fund - Direct - GROWTH",
]

gold = [
    "LIC MF Gold ETF Fund of Fund-Direct Plan-Growth",
    "SBI GOLD FUND- DIRECT PLAN - GROWTH",
    "Quantum Gold ETF FOF - Direct Plan Growth Option",
    "Kotak Gold Fund Growth - Direct",
    "HDFC Gold ETF Fund of Fund - Direct Plan",
]

silver = [
    "ICICI Prudential Silver ETF FOF - Direct Plan - Growth",
    "HDFC Silver ETF Fund of Fund - Growth Option - Direct Plan",
    "Nippon India Silver ETF FOF- Direct Plan-Growth Option",
    "SBI Silver ETF Fund of Fund- Direct Plan - Growth",
    "Axis Silver Fund of Fund- Direct Plan-Growth Option",
]

In [6]:
for fund in mid_cap+small_cap+debt+gold+silver:
    if fund not in mf_df['Scheme NAV Name'].values:
        print(fund)

In [7]:
fund_types = [mid_cap, small_cap, debt, gold, silver]
scheme_codes = {}
for fund_type in fund_types:
    for fund in fund_type:
        scheme_codes[fund] = mf_df[mf_df['Scheme NAV Name'] == fund]['Code'].values[0]

In [8]:
with open('data/fund_names.json', 'w') as f:
    json.dump({
        "mid_cap": {int(scheme_codes[fund]): fund for fund in mid_cap},
        "small_cap": {int(scheme_codes[fund]): fund for fund in small_cap},
        "debt": {int(scheme_codes[fund]): fund for fund in debt},
        "gold": {int(scheme_codes[fund]): fund for fund in gold},
        "silver": {int(scheme_codes[fund]): fund for fund in silver}
    }, f)

In [9]:
hist_nav_test = fetch_nav_history(scheme_codes["ICICI Prudential Silver ETF FOF - Direct Plan - Growth"], years=4, frequency='W')
hist_nav_test

            149775_nav
date
2022-09-30      9.1296
2022-10-07      9.8321
2022-10-14      9.0781
2022-10-21      8.9848
2022-10-28      9.2524
...                ...
2026-08-28     36.8949
2026-09-04     35.6601
2026-09-11     34.7266
2026-09-18     35.8754
2026-09-25     35.0253

[209 rows x 1 columns]

In [10]:
fund_df = build_portfolio_matrix(list(scheme_codes.values()), years=5, frequency='W')

Processing: 150584...
Processing: 151036...
Processing: 120403...
Processing: 120381...
Processing: 148073...
Processing: 118989...
Processing: 119775...
Processing: 147445...
Processing: 118668...
Processing: 140228...
Processing: 152237...
Processing: 129649...
Processing: 145678...
Processing: 147919...
Processing: 119212...
Processing: 145137...
Processing: 149019...
Processing: 119589...
Processing: 119556...
Processing: 120828...
Processing: 119539...
Processing: 119082...
Processing: 119382...
Processing: 130543...
Processing: 120582...
Processing: 118780...
Processing: 120670...
Processing: 118814...
Processing: 141588...
Processing: 118569...
Processing: 151974...
Processing: 119788...
Processing: 115132...
Processing: 119781...
Processing: 119132...
Processing: 149775...
Processing: 150737...
Processing: 149760...
Processing: 152735...
Processing: 150615...

In [11]:
fund_df

,150584,151036,120403,120381,148073,118989,119775,147445,118668,140228,...,151974,119788,115132,119781,119132,149775,150737,149760,152735,150615
date,,,,,,,,,,,,,,,,,,,,,
2021-10-01,NaN,NaN,98.19,174.65,27.99,97.924,78.214,21.226,2178.4584,54.945,...,NaN,14.8052,18.5574,19.8799,15.1776,NaN,NaN,NaN,NaN,NaN
2021-10-08,NaN,NaN,100.91,179.23,29.11,100.612,80.848,21.856,2258.9738,57.007,...,NaN,14.9255,18.7408,20.0239,15.2804,NaN,NaN,NaN,NaN,NaN
2021-10-15,NaN,NaN,104.21,183.60,29.85,103.484,82.530,22.367,2317.3708,58.673,...,NaN,15.2354,19.1666,20.4460,15.6518,NaN,NaN,NaN,NaN,NaN
2021-10-22,NaN,NaN,100.74,178.86,28.57,99.409,78.961,21.880,2207.8657,56.668,...,NaN,15.1551,19.0202,20.3204,15.5933,NaN,NaN,NaN,NaN,NaN
2021-10-29,NaN,NaN,100.46,176.34,27.99,98.153,78.900,21.591,2190.3414,55.861,...,NaN,15.2548,19.1498,20.4740,15.6409,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-08-28,23.899,547.8257,245.07,399.30,58.69,237.066,173.634,45.039,5045.8416,131.382,...,42.9449,48.3391,60.6083,63.9426,49.3748,36.8949,39.7713,36.7146,25.7161,41.2703
2026-09-04,23.628,544.9462,242.94,391.79,57.86,234.584,171.800,44.546,4987.3718,129.994,...,41.9569,46.9757,58.9694,62.1366,47.9712,35.6601,38.4496,35.4961,24.8638,39.9713
2026-09-11,23.424,544.7908,241.27,384.71,57.43,230.603,169.773,43.968,4943.7593,128.520,...,41.2154,46.2005,57.9200,61.0345,47.2103,34.7266,37.3741,34.5296,24.1662,38.9872
2026-09-18,23.425,542.1575,240.16,387.28,57.34,231.413,169.708,43.945,4948.3410,128.110,...,41.6183,46.7213,58.5296,61.7517,47.6720,35.8754,38.6629,35.6992,24.9839,40.2017
2026-09-25,22.979,527.4107,237.39,379.81,56.25,226.380,166.431,42.859,4886.5799,125.971,...,41.0266,45.9710,57.6652,60.8036,46.9367,35.0253,37.7476,34.8581,24.4204,39.2491

In [12]:
fund_df.isna().sum()

150584     49
151036     61
120403      0
120381      0
148073      0
118989      0
119775      0
147445      0
118668      0
140228      0
152237    117
129649      0
145678      0
147919      0
119212      0
145137      0
149019      0
119589      0
119556      0
120828      0
119539      0
119082      0
119382      0
130543      0
120582    261
118780      0
120670      0
118814      0
141588      0
118569      0
151974     96
119788      0
115132      0
119781      0
119132      0
149775     18
150737     56
149760     19
152735    146
150615     52
dtype: int64

In [13]:
fund_counts = {"mid_cap": 0, "small_cap": 0, "debt": 0, "gold": 0, "silver": 0}
for code, na_count in fund_df.isna().sum().items():
    if na_count >20:
        fund_name = mf_df[mf_df['Code'] == code]['Scheme NAV Name'].values[0]
        if fund_name in mid_cap:
            fund_counts["mid_cap"] += 1
        elif fund_name in small_cap:
            fund_counts["small_cap"] += 1
        elif fund_name in debt:
            fund_counts["debt"] += 1
        elif fund_name in gold:
            fund_counts["gold"] += 1
        elif fund_name in silver:
            fund_counts["silver"] += 1
        fund_df = fund_df.drop(columns=[code])
        print(f"Dropped {fund_name} due to {na_count} missing NAV data.")

print(fund_counts)

Dropped WhiteOak Capital Mid Cap Fund Direct Plan Growth due to 49 missing NAV data.
Dropped HSBC Midcap Fund - Direct Growth due to 61 missing NAV data.
Dropped Motilal Oswal Small Cap Fund - Direct - Growth due to 117 missing NAV data.
Dropped ICICI Prudential Dynamic Bond Fund - Direct Plan -  Growth due to 261 missing NAV data.
Dropped LIC MF Gold ETF Fund of Fund-Direct Plan-Growth due to 96 missing NAV data.
Dropped HDFC Silver ETF Fund of Fund - Growth Option - Direct Plan due to 56 missing NAV data.
Dropped SBI Silver ETF Fund of Fund- Direct Plan - Growth due to 146 missing NAV data.
Dropped Axis Silver Fund of Fund- Direct Plan-Growth Option due to 52 missing NAV data.
{'mid_cap': 2, 'small_cap': 1, 'debt': 1, 'gold': 1, 'silver': 3}

In [14]:
fund_df.index.min(), fund_df.index.max()

(Timestamp('2021-10-01 00:00:00'), Timestamp('2026-09-25 00:00:00'))

In [15]:
fund_df

,120403,120381,148073,118989,119775,147445,118668,140228,129649,145678,...,120670,118814,141588,118569,119788,115132,119781,119132,149775,149760
date,,,,,,,,,,,,,,,,,,,,,
2021-10-01,98.19,174.65,27.99,97.924,78.214,21.226,2178.4584,54.945,30.05,26.60,...,37.7279,48.4908,13.9817,83.9769,14.8052,18.5574,19.8799,15.1776,NaN,NaN
2021-10-08,100.91,179.23,29.11,100.612,80.848,21.856,2258.9738,57.007,30.97,27.83,...,37.7055,48.4997,13.9821,83.9837,14.9255,18.7408,20.0239,15.2804,NaN,NaN
2021-10-15,104.21,183.60,29.85,103.484,82.530,22.367,2317.3708,58.673,31.54,28.46,...,37.7742,48.5616,13.9927,84.1028,15.2354,19.1666,20.4460,15.6518,NaN,NaN
2021-10-22,100.74,178.86,28.57,99.409,78.961,21.880,2207.8657,56.668,30.42,26.82,...,37.7815,48.6085,14.0000,84.1232,15.1551,19.0202,20.3204,15.5933,NaN,NaN
2021-10-29,100.46,176.34,27.99,98.153,78.900,21.591,2190.3414,55.861,29.59,26.51,...,37.8249,48.5738,13.9931,84.0859,15.2548,19.1498,20.4740,15.6409,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-08-28,245.07,399.30,58.69,237.066,173.634,45.039,5045.8416,131.382,67.95,66.14,...,53.7293,67.1539,19.3408,115.9812,48.3391,60.6083,63.9426,49.3748,36.8949,36.7146
2026-09-04,242.94,391.79,57.86,234.584,171.800,44.546,4987.3718,129.994,67.76,66.18,...,53.8203,67.3374,19.3902,116.3378,46.9757,58.9694,62.1366,47.9712,35.6601,35.4961
2026-09-11,241.27,384.71,57.43,230.603,169.773,43.968,4943.7593,128.520,68.18,66.35,...,53.7778,67.2849,19.3771,116.3843,46.2005,57.9200,61.0345,47.2103,34.7266,34.5296
2026-09-18,240.16,387.28,57.34,231.413,169.708,43.945,4948.3410,128.110,67.89,65.99,...,53.8184,67.2989,19.3834,116.3699,46.7213,58.5296,61.7517,47.6720,35.8754,35.6992
2026-09-25,237.39,379.81,56.25,226.380,166.431,42.859,4886.5799,125.971,67.20,66.59,...,53.7491,67.1876,19.3594,116.3100,45.9710,57.6652,60.8036,46.9367,35.0253,34.8581

In [16]:
fund_df =fund_df.ffill().dropna()
fund_df.index.min(), fund_df.index.max()

(Timestamp('2022-02-11 00:00:00'), Timestamp('2026-09-25 00:00:00'))

In [17]:
fund_df

,120403,120381,148073,118989,119775,147445,118668,140228,129649,145678,...,120670,118814,141588,118569,119788,115132,119781,119132,149775,149760
date,,,,,,,,,,,,,,,,,,,,,
2022-02-11,98.86,172.18,27.83,98.162,78.594,21.414,2160.3426,54.993,30.50,27.56,...,38.2218,49.2521,14.1726,85.0425,15.4975,19.4375,20.7904,15.9089,10.1411,10.1177
2022-02-18,96.81,167.86,27.01,95.962,77.679,21.049,2113.1932,53.577,29.77,26.83,...,38.3254,49.3163,14.1876,85.1572,15.8451,19.8919,21.1214,16.2909,10.3756,10.3444
2022-02-25,93.84,162.92,26.36,93.215,75.638,20.274,2065.2842,52.545,28.94,26.17,...,38.3340,49.3455,14.1892,85.1980,15.9925,20.1231,21.2871,16.4963,10.5301,10.4836
2022-03-04,91.67,159.54,25.83,91.673,74.236,20.100,2016.5119,51.524,28.94,26.01,...,38.2722,49.3192,14.1822,85.1571,16.3622,20.5959,21.7396,16.8199,10.9621,10.9426
2022-03-11,94.08,164.13,26.36,94.305,76.265,20.530,2048.6223,52.904,29.53,26.72,...,38.2622,49.3431,14.1846,85.1472,16.5093,20.8759,21.8689,17.0668,11.2350,11.2692
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-08-28,245.07,399.30,58.69,237.066,173.634,45.039,5045.8416,131.382,67.95,66.14,...,53.7293,67.1539,19.3408,115.9812,48.3391,60.6083,63.9426,49.3748,36.8949,36.7146
2026-09-04,242.94,391.79,57.86,234.584,171.800,44.546,4987.3718,129.994,67.76,66.18,...,53.8203,67.3374,19.3902,116.3378,46.9757,58.9694,62.1366,47.9712,35.6601,35.4961
2026-09-11,241.27,384.71,57.43,230.603,169.773,43.968,4943.7593,128.520,68.18,66.35,...,53.7778,67.2849,19.3771,116.3843,46.2005,57.9200,61.0345,47.2103,34.7266,34.5296
2026-09-18,240.16,387.28,57.34,231.413,169.708,43.945,4948.3410,128.110,67.89,65.99,...,53.8184,67.2989,19.3834,116.3699,46.7213,58.5296,61.7517,47.6720,35.8754,35.6992
2026-09-25,237.39,379.81,56.25,226.380,166.431,42.859,4886.5799,125.971,67.20,66.59,...,53.7491,67.1876,19.3594,116.3100,45.9710,57.6652,60.8036,46.9367,35.0253,34.8581

In [18]:
fund_df.to_csv('data/fund_navs.csv', index=True)